# Generated by Django 2.1 on 2018-08-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrotServer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='param',
            field=models.IntegerField(blank=True),
        ),
    ]
